### PR TITLE
Add tests for Lazy and Provider.

### PR DESCRIPTION
**Pull request by runningcode**
References #98

### CODE REVIEW

**Comment by JakeWharton** [comment]
I think we want these tests:
 * Provider calls unscoped binding every time `get()` is called, instances are different
 * Provider calls scoped binding once even though `get()` is called twice, instances are same
 * Lazy calls unscoped binding once even though `get()` is called twice, instances are same
 * Two Lazy instances _each_ call unscoped binding once, instances are different
 * Lazy calls scoped binding once when `get()` invoked twice

I would just expose these on the component instead of injecting them into a type like
```java
interface Component {
  Provider<String> string();
}
```

**Comment by JakeWharton** [comment]
There are some checks for provider in the multibindings which do this already which we should copy to keep their structure the same.

**Comment by TWiStErRob** [comment]
Should it be tested that `Lazy` is actually lazy? i.e. the `@Provides` method is not called until `Lazy.get`?

**Comment by JakeWharton** [comment]
Yes. The maps ones have that structure.

**Comment by runningcode** [comment]
Added tests as specified!

**Comment by JakeWharton** [comment]
Thanks! I have this mostly implemented on a branch. Time to rebase and test!

**Pull request merged**
